apiVersion: v1
kind: Service
metadata:
  name: backstage-demo
  labels:
    app: backstage-demo
    backstage.io/kubernetes-id: backstage-demo
spec:
  selector:
    app: backstage-demo
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
